// ------------- create add to card 
export const CREATE_CART_PRODUCT_REQUEST = "CREATE_CART_PRODUCT_REQUEST";
export const CREATE_CART_PRODUCT_REQUEST_FAIL = "CREATE_CART_PRODUCT_REQUEST_FAIL";
export const CREATE_CART_PRODUCT_SUCCESS = "CREATE_CART_PRODUCT_SUCCESS";
export const CREATE_CART_PRODUCT_ERROR = "CREATE_CART_PRODUCT_ERROR";

// ------ get card data 

export const GET_CART_PRODUCT_REQUEST = "GET_CART_PRODUCT_REQUEST";
export const GET_CART_PRODUCT_REQUEST_FAIL = "GET_CART_PRODUCT_REQUEST_FAIL";
export const GET_CART_PRODUCT_SUCCESS = "GET_CART_PRODUCT_SUCCESS";
export const GET_CART_PRODUCT_ERROR = "GET_CART_PRODUCT_ERROR";

// ----- delete cart item 

export const DELETE_CART_PRODUCT_REQUEST = "DELETE_CART_PRODUCT_REQUEST";
export const DELETE_CART_PRODUCT_REQUEST_FAIL = "DELETE_CART_PRODUCT_REQUEST_FAIL";
export const DELETE_CART_PRODUCT_SUCCESS = "DELETE_CART_PRODUCT_SUCCESS";
export const DELETE_CART_PRODUCT_ERROR = "DELETE_CART_PRODUCT_ERROR";

