// ------------ create order
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_REQUEST_FAIL = "CREATE_ORDER_REQUEST_FAIL";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAIL = "ORDER_FAIL";
export const ORDER_REQUEST = "ORDER_REQUEST";

// ========= get all orders
export const GET_ALL_ORDER_REQUEST = "GET_ALL_ORDER_REQUEST";
export const GET_ALL_ORDER_REQUEST_FAIL = "GET_ALL_ORDER_REQUEST_FAIL";
export const GET_ALL_ORDER_SUCCESS = "GET_ALL_ORDER_SUCCESS";
export const GET_ALL_ORDER_ERROR = "GET_ALL_ORDER_ERROR";

// ========= update order status
export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST";
export const UPDATE_ORDER_STATUS_REQUEST_FAIL =
  "UPDATE_ORDER_STATUS_REQUEST_FAIL";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_ERROR = "UPDATE_ORDER_STATUS_ERROR";

// ========= download file
export const DOWNLOAD_FILE_REQUEST = "DOWNLOAD_FILE_REQUEST";
export const DOWNLOAD_FILE_REQUEST_FAIL = "DOWNLOAD_FILE_REQUEST_FAIL";
export const DOWNLOAD_FILE_SUCCESS = "DOWNLOAD_FILE_SUCCESS";
export const DOWNLOAD_FILE_ERROR = "DOWNLOAD_FILE_ERROR";

// ------ status update
export const STATUS_UPDATE_REQUEST = "STATUS_UPDATE_REQUEST";
export const STATUS_UPDATE_REQUEST_FAIL = "STATUS_UPDATE_REQUEST_FAIL";
export const STATUS_UPDATE_SUCCESS = "STATUS_UPDATE_SUCCESS";
export const STATUS_UPDATE_ERROR = "STATUS_UPDATE_ERROR";

// ------ Transcations
export const TRANSCATION_REQUEST = "TRANSCATION_REQUEST";
export const TRANSCATION_REQUEST_FAIL = "TRANSCATION_REQUEST_FAIL";
export const TRANSCATION_SUCCESS = "TRANSCATION_SUCCESS";
export const TRANSCATION_ERROR = "TRANSCATION_ERROR";
