// ======================================= login
export const LOGIN_USER_REQUEST = "Login_user_request";
export const LOGIN_USER_FAIL = "Login_user_fail";
export const LOGIN_USER_SUCCESS = "Login_user_success";
export const LOGIN_USER_ERROR = "Login_user_error";

// =========================== registration
export const REGISTRATION_USER_REQUEST = "REGISTRATION_user_request";
export const REGISTRATION_USER_FAIL = "REGISTRATION_user_fail";
export const REGISTRATION_USER_SUCCESS = "REGISTRATION_user_success";
export const REGISTRATION_USER_ERROR = "REGISTRATION_user_error";

// ============= logout
export const LOGOUT_USER_REQUEST = "LOGOUT_user_request";
export const LOGOUT_USER_FAIL = "LOGOUT_user_fail";
export const LOGOUT_USER_SUCCESS = "LOGOUT_user_success";
export const LOGOUT_USER_ERROR = "LOGOUT_user_error";

// ============================= user verification

export const VALID_USER_REQUEST = "VALID_User_Request";
export const VALID_USER_FAIL = "VALID_User_Fali";
export const VALID_USER_SUCCESS = "VALID_User_Success";
export const VALID_USER_ERROR = "VALID_User_Error";

// ========================= product Variables
export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR";

// ===== edit PRODUCT
export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR";

// ============================== all Product
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";
// ============================== all Product
export const GET_ADMIN_PRODUCT_REQUEST = "GET_ADMIN_PRODUCT_REQUEST";
export const GET_ADMIN_PRODUCT_FAIL = "GET_ADMIN_PRODUCT_FAIL";
export const GET_ADMIN_PRODUCT_SUCCESS = "GET_ADMIN_PRODUCT_SUCCESS";
export const GET_ADMIN_PRODUCT_ERROR = "GET_ADMIN_PRODUCT_ERROR";

// ------------- create category
export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_ERROR = "CREATE_CATEGORY_ERROR";

// ============================== all Category
export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_ERROR = "GET_CATEGORY_ERROR";
// ============================== all Category for user
export const GET_CATEGORY_FOR_USER_REQUEST = "GET_CATEGORY_FOR_USER_REQUEST";
export const GET_CATEGORY_FOR_USER_FAIL = "GET_CATEGORY_FOR_USER_FAIL";
export const GET_CATEGORY_FOR_USER_SUCCESS = "GET_CATEGORY_FOR_USER_SUCCESS";
export const GET_CATEGORY_FOR_USER_ERROR = "GET_CATEGORY_FOR_USER_ERROR";

// ===== update category
export const EDIT_CATEGORY_REQUEST = "EDIT_CATEGORY_REQUEST";
export const EDIT_CATEGORY_FAIL = "EDIT_CATEGORY_FAIL";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";
export const EDIT_CATEGORY_ERROR = "EDIT_CATEGORY_ERROR";

// ============================== all SUB_CATEGORY
export const GET_SUB_CATEGORY_REQUEST = "GET_SUB_CATEGORY_REQUEST";
export const GET_SUB_CATEGORY_FAIL = "GET_SUB_CATEGORY_FAIL";
export const GET_SUB_CATEGORY_SUCCESS = "GET_SUB_CATEGORY_SUCCESS";
export const GET_SUB_CATEGORY_ERROR = "GET_SUB_CATEGORY_ERROR";

// =============== create SubCategory
export const CREATE_SUB_CATEGORY_REQUEST = "CREATE_SUB_CATEGORY_REQUEST";
export const CREATE_SUB_CATEGORY_FAIL = "CREATE_SUB_CATEGORY_FAIL";
export const CREATE_SUB_CATEGORY_SUCCESS = "CREATE_SUB_CATEGORY_SUCCESS";
export const CREATE_SUB_CATEGORY_ERROR = "CREATE_SUB_CATEGORY_ERROR";

// === edit subcategory
export const EDIT_SUB_CATEGORY_REQUEST = "EDIT_SUB_CATEGORY_REQUEST";
export const EDIT_SUB_CATEGORY_FAIL = "EDIT_SUB_CATEGORY_FAIL";
export const EDIT_SUB_CATEGORY_SUCCESS = "EDIT_SUB_CATEGORY_SUCCESS";
export const EDIT_SUB_CATEGORY_ERROR = "EDIT_SUB_CATEGORY_ERROR";

// --------------- get single product
export const GET_SINGLE_PRODUCT_REQUEST = "GET_SINGLE_PRODUCT_REQUEST";
export const GET_SINGLE_PRODUCT_FAIL = "GET_SINGLE_PRODUCT_FAIL";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR";

// ======== create user adress
export const CREATE_ADDRESS_REQUEST = "CREATE_ADDRESS_REQUEST";
export const CREATE_ADDRESS_FAIL = "CREATE_ADDRESS_FAIL";
export const CREATE_ADDRESS_SUCCESS = "CREATE_ADDRESS_SUCCESS";
export const CREATE_ADDRESS_ERROR = "CREATE_ADDRESS_ERROR";

// ---------- get user address
export const GET_ADDRESS_REQUEST = "GET_ADDRESS_REQUEST";
export const GET_ADDRESS_FAIL = "GET_ADDRESS_FAIL";
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS";
export const GET_ADDRESS_ERROR = "GET_ADDRESS_ERROR";
// ---------- update user address
export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST";
export const UPDATE_ADDRESS_FAIL = "UPDATE_ADDRESS_FAIL";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_ERROR = "UPDATE_ADDRESS_ERROR";

// ------- delete address
export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_FAIL = "DELETE_ADDRESS_FAIL";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_ERROR = "DELETE_ADDRESS_ERROR";

// ---------- get user Order
export const GET_ORDERS_USER_REQUEST = "GET_ORDERS_USER_REQUEST";
export const GET_ORDERS_USER_FAIL = "GET_ORDERS_USER_FAIL";
export const GET_ORDERS_USER_SUCCESS = "GET_ORDERS_USER_SUCCESS";
export const GET_ORDERS_USER_ERROR = "GET_ORDERS_USER_ERROR";

// ---- admin all users
export const GET_ADMIN_ALL_REQUEST = "GET_ADMIN_ALL_REQUEST";
export const GET_ADMIN_ALL_FAIL = "GET_ADMIN_ALL_FAIL";
export const GET_ADMIN_ALL_SUCCESS = "GET_ADMIN_ALL_SUCCESS";
export const GET_ADMIN_ALL_ERROR = "GET_ADMIN_ALL_ERROR";

// ---- Active or deActive user
export const ACTIVE_DEACTIVE_USER_REQUEST = "ACTIVE_DEACTIVE_USER_REQUEST";
export const ACTIVE_DEACTIVE_USER_FAIL = "ACTIVE_DEACTIVE_USER_FAIL";
export const ACTIVE_DEACTIVE_USER_SUCCESS = "ACTIVE_DEACTIVE_USER_SUCCESS";
export const ACTIVE_DEACTIVE_USER_ERROR = "ACTIVE_DEACTIVE_USER_ERROR";

// ---- user analytics
export const ANALYTICS_USER_REQUEST = "ANALYTICS_USER_REQUEST";
export const ANALYTICS_USER_FAIL = "ANALYTICS_USER_FAIL";
export const ANALYTICS_USER_SUCCESS = "ANALYTICS_USER_SUCCESS";
export const ANALYTICS_USER_ERROR = "ANALYTICS_USER_ERROR";

// ---- product discount
export const DISCOUNT_PRODUCT_REQUEST = "DISCOUNT_PRODUCT_REQUEST";
export const DISCOUNT_PRODUCT_FAIL = "DISCOUNT_PRODUCT_FAIL";
export const DISCOUNT_PRODUCT_SUCCESS = "DISCOUNT_PRODUCT_SUCCESS";
export const DISCOUNT_PRODUCT_ERROR = "DISCOUNT_PRODUCT_ERROR";

// ======== Update User Password
export const PASSWORD_UPDATE_REQUEST = "PASSWORD_UPDATE_REQUEST";
export const PASSWORD_UPDATE_FAIL = "PASSWORD_UPDATE_FAIL";
export const PASSWORD_UPDATE_SUCCESS = "PASSWORD_UPDATE_SUCCESS";
export const PASSWORD_UPDATE_ERROR = "PASSWORD_UPDATE_ERROR";

// ============ user email password update
export const PROFILE_UPDATE_REQUEST = "PROFILE_UPDATE_REQUEST";
export const PROFILE_UPDATE_FAIL = "PROFILE_UPDATE_FAIL";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_ERROR = "PROFILE_UPDATE_ERROR";

// ============ Create Pakcage
export const PACKAGE_CREATE_REQUEST = "PACKAGE_CREATE_REQUEST";
export const PACKAGE_CREATE_FAIL = "PACKAGE_CREATE_FAIL";
export const PACKAGE_CREATE_SUCCESS = "PACKAGE_CREATE_SUCCESS";
export const PACKAGE_CREATE_ERROR = "PACKAGE_CREATE_ERROR";
