// --------- create vendor 
export const CREATE_VENDOR_REQUEST = "CREATE_VENDOR_REQUEST";
export const CREATE_VENDOR_REQUEST_FAIL = "CREATE_VENDOR_REQUEST_FAIL";
export const CREATE_VENDOR_SUCCESS = "CREATE_VENDOR_SUCCESS";
export const CREATE_VENDOR_ERROR = "CREATE_VENDOR_ERROR";

// ---------- get all vendor 
export const GET_VENDOR_REQUEST = "GET_VENDOR_REQUEST";
export const GET_VENDOR_REQUEST_FAIL = "GET_VENDOR_REQUEST_FAIL";
export const GET_VENDOR_SUCCESS = "GET_VENDOR_SUCCESS";
export const GET_VENDOR_ERROR = "GET_VENDOR_ERROR";

// ------ assigned  
export const ASSIGNED_VENDOR_REQUEST = "ASSIGNED_VENDOR_REQUEST";
export const ASSIGNED_VENDOR_REQUEST_FAIL = "ASSIGNED_VENDOR_REQUEST_FAIL";
export const ASSIGNED_VENDOR_SUCCESS = "ASSIGNED_VENDOR_SUCCESS";
export const ASSIGNED_VENDOR_ERROR = "ASSIGNED_VENDOR_ERROR";

// ---- updateactive 
export const UPDATE_VENDOR_REQUEST = "UPDATE_VENDOR_REQUEST";
export const UPDATE_VENDOR_REQUEST_FAIL = "UPDATE_VENDOR_REQUEST_FAIL";
export const UPDATE_VENDOR_SUCCESS = "UPDATE_VENDOR_SUCCESS";
export const UPDATE_VENDOR_ERROR = "UPDATE_VENDOR_ERROR";
